const CA_PROVINCES = {
  AB: "AB", ALBERTA: "AB", BC: "BC", "BRITISH COLUMBIA": "BC", MB: "MB", MANITOBA: "MB", NB: "NB", "NEW BRUNSWICK": "NB", NL: "NL", "NEWFOUNDLAND AND LABRADOR": "NL", NEWFOUNDLAND: "NL", NS: "NS", "NOVA SCOTIA": "NS", NT: "NT", "NORTHWEST TERRITORIES": "NT", NU: "NU", NUNAVUT: "NU", ON: "ON", ONTARIO: "ON", PE: "PE", "PRINCE EDWARD ISLAND": "PE", QC: "QC", QUEBEC: "QC", "QUÉBEC": "QC", SK: "SK", SASKATCHEWAN: "SK", YT: "YT", YUKON: "YT",
};
const US_STATES = { AL: "AL", ALABAMA: "AL", AK: "AK", ALASKA: "AK", AZ: "AZ", ARIZONA: "AZ", AR: "AR", ARKANSAS: "AR", CA: "CA", CALIFORNIA: "CA", CO: "CO", COLORADO: "CO", CT: "CT", CONNECTICUT: "CT", DE: "DE", DELAWARE: "DE", FL: "FL", FLORIDA: "FL", GA: "GA", GEORGIA: "GA", HI: "HI", HAWAII: "HI", ID: "ID", IDAHO: "ID", IL: "IL", ILLINOIS: "IL", IN: "IN", INDIANA: "IN", IA: "IA", IOWA: "IA", KS: "KS", KANSAS: "KS", KY: "KY", KENTUCKY: "KY", LA: "LA", LOUISIANA: "LA", ME: "ME", MAINE: "ME", MD: "MD", MARYLAND: "MD", MA: "MA", MASSACHUSETTS: "MA", MI: "MI", MICHIGAN: "MI", MN: "MN", MINNESOTA: "MN", MS: "MS", MISSISSIPPI: "MS", MO: "MO", MISSOURI: "MO", MT: "MT", MONTANA: "MT", NE: "NE", NEBRASKA: "NE", NV: "NV", NEVADA: "NV", NH: "NH", "NEW HAMPSHIRE": "NH", NJ: "NJ", "NEW JERSEY": "NJ", NM: "NM", "NEW MEXICO": "NM", NY: "NY", "NEW YORK": "NY", NC: "NC", "NORTH CAROLINA": "NC", ND: "ND", "NORTH DAKOTA": "ND", OH: "OH", OHIO: "OH", OK: "OK", OKLAHOMA: "OK", OR: "OR", OREGON: "OR", PA: "PA", PENNSYLVANIA: "PA", RI: "RI", "RHODE ISLAND": "RI", SC: "SC", "SOUTH CAROLINA": "SC", SD: "SD", "SOUTH DAKOTA": "SD", TN: "TN", TENNESSEE: "TN", TX: "TX", TEXAS: "TX", UT: "UT", UTAH: "UT", VT: "VT", VERMONT: "VT", VA: "VA", VIRGINIA: "VA", WA: "WA", WASHINGTON: "WA", WV: "WV", "WEST VIRGINIA": "WV", WI: "WI", WISCONSIN: "WI", WY: "WY", WYOMING: "WY" };
function clean(value) { return String(value || "").trim().toUpperCase().replace(/\s+/g, " "); }
function countryCode(country) { const c = clean(country); if (c === "CANADA" || c === "CA") return "CA"; if (c === "UNITED STATES" || c === "UNITED STATES OF AMERICA" || c === "USA" || c === "US") return "US"; return c; }
export function normalizeRegionCode(country, provinceState) { const raw = clean(provinceState); if (!raw) return null; if (/^[A-Z]{2}-[A-Z]{2}$/.test(raw)) return raw; const c = countryCode(country || "CA"); const code = c === "CA" ? CA_PROVINCES[raw] : c === "US" ? US_STATES[raw] : raw; return code ? `${c}-${code}` : null; }
export function isRegionExcluded(regionCode, excludeRegions) { if (!regionCode || !Array.isArray(excludeRegions)) return false; return excludeRegions.some((value) => { const rule = clean(value); return rule === regionCode || (rule.endsWith("-*") && regionCode.startsWith(rule.slice(0, -1))); }); }
export function buyerAddressFields(address = {}) { return { country: address.country || "Canada", provinceState: address.province_state || address.state || address.province || "" }; }
export function resolveShippingScope({ address, shopProvince, allowNational, nationalRegions, shipToUs, excludeRegions, method }) { if (method === "pickup") return { scope: "home", region: null, pickup: true }; const { country, provinceState } = buyerAddressFields(address); const region = normalizeRegionCode(country, provinceState); if (!region) return { scope: "blocked", reason: "Add a valid province/state to calculate shipping." }; if (isRegionExcluded(region, excludeRegions || [])) return { scope: "blocked", reason: "This shop does not ship to your region." }; const home = normalizeRegionCode("Canada", shopProvince); if (home && region === home) return { scope: "home", region }; if (region.startsWith("US-")) { if (!shipToUs) return { scope: "blocked", reason: "This shop does not ship to the United States." }; return { scope: "us", region }; } if (!allowNational) return { scope: "blocked", reason: "This shop only ships within its home province." }; if (Array.isArray(nationalRegions) && nationalRegions.length && !nationalRegions.map((r) => clean(r)).includes(region)) return { scope: "blocked", reason: "This shop does not ship to your province." }; return { scope: "national", region }; }
export function resolveShippingRate({ settings, method, scope, subtotalCents }) { const src = settings || defaultShippingSettings(); const m = method === "express" || method === "pickup" ? method : "standard"; if (m === "express" && src.express_enabled === false) return null; if (m === "pickup" && src.pickup_enabled === false) return null; const s = scope === "national" || scope === "us" ? scope : "home"; const freeOver = Number(src[`${m}_${s}_free_over_cents`]); if (Number.isFinite(freeOver) && freeOver > 0 && subtotalCents >= freeOver) return { cents: 0, minDays: src[`${m}_${s}_min_days`] ?? null, maxDays: src[`${m}_${s}_max_days`] ?? null, label: labelFor(m, s, src, true) }; let cents = Number(src[`${m}_${s}_flat_cents`]) || 0; if (m === "express" && src.express_rate_mode === "surcharge") cents = (Number(src.express_home_flat_cents) || 0) + (Number(src.express_surcharge_cents) || 0); return { cents, minDays: src[`${m}_${s}_min_days`] ?? null, maxDays: src[`${m}_${s}_max_days`] ?? null, label: labelFor(m, s, src, false) }; }
function labelFor(method, scope, settings, free) { const name = method === "pickup" ? "Pickup" : method === "express" ? "Express" : "Standard"; if (free) return `${name} · Free`; const min = settings[`${method}_${scope}_min_days`]; const max = settings[`${method}_${scope}_max_days`]; return `${name}${min != null && max != null ? ` · ${min}–${max} business days` : ""}`; }
export function defaultShippingSettings() { return { fulfillment_province: "ON", allow_national: true, national_regions: [], ship_to_us: false, exclude_regions: [], standard_home_flat_cents: 800, standard_home_min_days: 3, standard_home_max_days: 7, standard_national_flat_cents: 1200, standard_national_min_days: 5, standard_national_max_days: 10, standard_us_flat_cents: 2500, standard_us_min_days: 7, standard_us_max_days: 14, express_enabled: true, express_rate_mode: "flat", express_surcharge_cents: 0, express_home_flat_cents: 1500, express_home_min_days: 1, express_home_max_days: 3, express_national_flat_cents: 2200, express_national_min_days: 2, express_national_max_days: 4, express_us_flat_cents: 3500, express_us_min_days: 3, express_us_max_days: 6, pickup_enabled: true, pickup_ready_hours: 24, pickup_home_flat_cents: 0, pickup_national_flat_cents: 0, pickup_us_flat_cents: 0 }; }
